; Sound Effects for song Untitled, version 2.0, generated by Arkos Tracker 2.

sfx_SoundEffects
sfx_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
sfx_SoundEffectsDisarkPointerRegionStart0
	dw sfx_SoundEffects_Sound1	; Sound effect 1.
	dw sfx_SoundEffects_Sound2	; Sound effect 2.
	dw sfx_SoundEffects_Sound3	; Sound effect 3.
	dw sfx_SoundEffects_Sound4	; Sound effect 4.
	dw sfx_SoundEffects_Sound5	; Sound effect 5.
	dw sfx_SoundEffects_Sound6	; Sound effect 6.
	dw sfx_SoundEffects_Sound7	; Sound effect 7.
	dw sfx_SoundEffects_Sound8	; Sound effect 8.
	dw sfx_SoundEffects_Sound9	; Sound effect 9.
	dw sfx_SoundEffects_Sound10	; Sound effect 10.
	dw sfx_SoundEffects_Sound11	; Sound effect 11.
	dw sfx_SoundEffects_Sound12	; Sound effect 12.
	dw sfx_SoundEffects_Sound13	; Sound effect 13.
sfx_SoundEffectsDisarkPointerRegionEnd0

sfx_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
sfx_SoundEffects_Sound1
	db 0	; Speed

sfx_SoundEffects_Sound1_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 239	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 246	; Software period.

	db 4	; End of the sound effect.

; Sound effect 2.
sfx_SoundEffects_Sound2
	db 0	; Speed

sfx_SoundEffects_Sound2_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 602	; Software period.

	db 189	; Soft only. Volume: 15.
	db 8	; Noise: 8.
	dw 638	; Software period.

	db 185	; Soft only. Volume: 14.
	db 2	; Noise: 2.
	dw 804	; Software period.

	db 181	; Soft only. Volume: 13.
	db 16	; Noise: 16.
	dw 426	; Software period.

	db 177	; Soft only. Volume: 12.
	db 2	; Noise: 2.
	dw 451	; Software period.

	db 173	; Soft only. Volume: 11.
	db 2	; Noise: 2.
	dw 478	; Software period.

	db 165	; Soft only. Volume: 9.
	db 16	; Noise: 16.
	dw 716	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 239	; Software period.

	db 153	; Soft only. Volume: 6.
	db 7	; Noise: 7.
	dw 159	; Software period.

	db 4	; End of the sound effect.

; Sound effect 3.
sfx_SoundEffects_Sound3
	db 0	; Speed

sfx_SoundEffects_Sound3_Loop	db 189	; Soft only. Volume: 15.
	db 5	; Noise: 5.
	dw 119	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 239	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 159	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 239	; Software period.

	db 4	; End of the sound effect.

; Sound effect 4.
sfx_SoundEffects_Sound4
	db 0	; Speed

sfx_SoundEffects_Sound4_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 119	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 60	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 95	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 47	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 80	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 40	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 30	; Hardware period.
	dw 956	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 30	; Hardware period.
	dw 956	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 4	; End of the sound effect.

; Sound effect 5.
sfx_SoundEffects_Sound5
	db 0	; Speed

sfx_SoundEffects_Sound5_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 119	; Software period.

	db 181	; Soft only. Volume: 13.
	db 31	; Noise: 31.
	dw 239	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 179	; Software period.

	db 157	; Soft only. Volume: 7.
	db 15	; Noise: 15.
	dw 239	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 239	; Software period.

	db 4	; End of the sound effect.

; Sound effect 6.
sfx_SoundEffects_Sound6
	db 0	; Speed

sfx_SoundEffects_Sound6_Loop	db 189	; Soft only. Volume: 15.
	db 8	; Noise: 8.
	dw 239	; Software period.

	db 169	; Soft only. Volume: 10.
	db 1	; Noise: 1.
	dw 426	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 568	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 638	; Software period.

	db 4	; End of the sound effect.

; Sound effect 7.
sfx_SoundEffects_Sound7
	db 0	; Speed

sfx_SoundEffects_Sound7_Loop	db 189	; Soft only. Volume: 15.
	db 6	; Noise: 6.
	dw 676	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 239	; Software period.

	db 189	; Soft only. Volume: 15.
	db 2	; Noise: 2.
	dw 239	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 338	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 4	; End of the sound effect.

; Sound effect 8.
sfx_SoundEffects_Sound8
	db 0	; Speed

sfx_SoundEffects_Sound8_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 113	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 213	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 106	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 201	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 100	; Software period.

	db 4	; End of the sound effect.

; Sound effect 9.
sfx_SoundEffects_Sound9
	db 0	; Speed

sfx_SoundEffects_Sound9_Loop	db 0	; No soft, no hard. Volume: 0.

	db 4	; End of the sound effect.

; Sound effect 10.
sfx_SoundEffects_Sound10
	db 0	; Speed

sfx_SoundEffects_Sound10_Loop	db 19	; Soft and Hard. Env: 10.
	dw 60	; Hardware period.
	dw 239	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 15	; Hardware period.
	dw 236	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 58	; Hardware period.
	dw 232	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 14	; Hardware period.
	dw 230	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 57	; Hardware period.
	dw 228	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 14	; Hardware period.
	dw 226	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 56	; Hardware period.
	dw 223	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 14	; Hardware period.
	dw 220	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 54	; Hardware period.
	dw 216	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 13	; Hardware period.
	dw 214	; Software period.

	db 4	; End of the sound effect.

; Sound effect 11.
sfx_SoundEffects_Sound11
	db 0	; Speed

sfx_SoundEffects_Sound11_Loop	db 3	; Soft and Hard. Env: 8.
	dw 2	; Hardware period.
	dw 27	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 3	; Hardware period.
	dw 47	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 2	; Hardware period.
	dw 30	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 5	; Hardware period.
	dw 75	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 3	; Hardware period.
	dw 47	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 5	; Hardware period.
	dw 75	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 12	; Hardware period.
	dw 190	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 19	; Hardware period.
	dw 301	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 12	; Hardware period.
	dw 190	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 34	; Hardware period.
	dw 536	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 50	; Hardware period.
	dw 804	; Software period.

	db 4	; End of the sound effect.

; Sound effect 12.
sfx_SoundEffects_Sound12
	db 0	; Speed

sfx_SoundEffects_Sound12_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 239	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 253	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 266	; Software period.

	db 4	; End of the sound effect.

; Sound effect 13.
sfx_SoundEffects_Sound13
	db 0	; Speed

sfx_SoundEffects_Sound13_Loop	db 200	; No soft, no hard. Volume: 9.
	db 27	; Noise: 27.

	db 216	; No soft, no hard. Volume: 11.
	db 5	; Noise: 5.

	db 248	; No soft, no hard. Volume: 15.
	db 8	; Noise: 8.

	db 232	; No soft, no hard. Volume: 13.
	db 16	; Noise: 16.

	db 216	; No soft, no hard. Volume: 11.
	db 5	; Noise: 5.

	db 4	; End of the sound effect.

sfx_SoundEffectsDisarkByteRegionEnd1
